#!/bin/bash

. /etc/os-release
. /etc/armbian-release

KERNELID=$(uname -r)

#microplay-hub Logo
echo -e "\033[38;5;208m"
echo -e "\033[38;5;208m───╔╗─────────────────╔╗──╔╗"
echo -e "\033[38;5;208m╔══╬╬═╦╦╦═╦═╦╗╔═╗╔╦╦══╣╚╦╦╣╚╗"
echo -e "\033[38;5;208m║║║║║═╣╔╣╬║╬║╚╣╬╚╣║╠══╣║║║║╬║"
echo -e "\033[38;5;208m╚╩╩╩╩═╩╝╚═╣╔╩═╩══╬╗║──╚╩╩═╩═╝"
echo -e "\033[38;5;208m──────────╚╝─────╚═╝"

printf '\e[0;32mWelcome to \e[0;32mARMBIAN\x1B[0m %s %s\n' "$PRETTY_NAME $KERNELID"
